import { RunReport, Suggestion, GitHubIssue, GitHubIssueCreationResult } from './types';

/**
 * GitHub Issue Generator
 * 
 * Converts LLM suggestions and run reports into GitHub issues
 */

/**
 * Generate a GitHub issue from a suggestion
 */
export function generateIssueFromSuggestion(
  suggestion: Suggestion,
  runReport: RunReport
): GitHubIssue {
  const body = `
## Summary
${suggestion.description}

## Source
- **Scenario**: ${runReport.scenarioName}
- **Run ID**: \`${runReport.id}\`
- **Run Status**: ${runReport.status}
- **Severity**: ${suggestion.severity}

## LLM Evaluation Context
${runReport.llmEvaluation ? `
- **Overall Score**: ${runReport.llmEvaluation.overallScore}/5
- **Relevant Dimensions**:
${runReport.llmEvaluation.dimensions.map(d => `  - ${d.name}: ${d.score}/5`).join('\n')}
` : 'No LLM evaluation available'}

## Repro Steps
${runReport.steps.map((step, i) => `${i + 1}. ${step.stepId}`).join('\n')}

## Artifacts
- Logs: \`${runReport.artifacts.logs}\`
${runReport.artifacts.screenshots.length > 0 ? `- Screenshots: ${runReport.artifacts.screenshots.length} captured` : ''}
${runReport.artifacts.video ? `- Video: \`${runReport.artifacts.video}\`` : ''}
${runReport.artifacts.chatTranscript ? `- Chat Transcript: \`${runReport.artifacts.chatTranscript}\`` : ''}

---
*Generated by VS Code Scenario Runner*
`.trim();

  return {
    title: suggestion.title,
    body,
    labels: [...suggestion.labels, `severity:${suggestion.severity}`, 'scenario-runner'],
  };
}

/**
 * Generate a GitHub issue from a failed run
 */
export function generateIssueFromFailure(runReport: RunReport): GitHubIssue {
  const failedSteps = runReport.steps.filter(s => s.status === 'failed');
  const failedAssertions = runReport.assertions.filter(a => !a.passed);
  
  const body = `
## Summary
Scenario "${runReport.scenarioName}" failed during automated testing.

## Failure Details
${runReport.error ? `**Error**: ${runReport.error}` : ''}

### Failed Steps
${failedSteps.length > 0 
  ? failedSteps.map(s => `- \`${s.stepId}\`: ${s.error || 'Unknown error'}`).join('\n')
  : 'No step failures'}

### Failed Assertions
${failedAssertions.length > 0
  ? failedAssertions.map(a => `- \`${a.assertionId}\`: Expected \`${a.expected}\`, got \`${a.actual}\``).join('\n')
  : 'No assertion failures'}

## Run Information
- **Run ID**: \`${runReport.id}\`
- **Started**: ${runReport.startTime}
- **Duration**: ${runReport.duration}ms
- **Environment**:
  - VS Code: ${runReport.environment.vscodeVersion}
  - Platform: ${runReport.environment.platform}

## Steps Executed
${runReport.steps.map((step, i) => {
  const icon = step.status === 'passed' ? '✅' : step.status === 'failed' ? '❌' : '⏭️';
  return `${i + 1}. ${icon} \`${step.stepId}\` (${step.duration}ms)`;
}).join('\n')}

## Artifacts
- Logs: \`${runReport.artifacts.logs}\`
${runReport.artifacts.screenshots.length > 0 ? `- Screenshots: ${runReport.artifacts.screenshots.join(', ')}` : ''}
${runReport.artifacts.video ? `- Video: \`${runReport.artifacts.video}\`` : ''}

---
*Generated by VS Code Scenario Runner*
`.trim();

  return {
    title: `[Scenario Failure] ${runReport.scenarioName}`,
    body,
    labels: ['bug', 'scenario-runner', 'needs-triage'],
  };
}

/**
 * Mock GitHub issue creation
 */
export async function createGitHubIssue(
  _issue: GitHubIssue,
  repo: string
): Promise<GitHubIssueCreationResult> {
  // Simulate API latency
  await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 500));
  
  // Mock successful creation
  const issueNumber = Math.floor(Math.random() * 10000) + 1;
  
  return {
    success: true,
    issueNumber,
    issueUrl: `https://github.com/${repo}/issues/${issueNumber}`,
  };
}

/**
 * Format issue for preview
 */
export function formatIssuePreview(issue: GitHubIssue): string {
  return `
# ${issue.title}

**Labels**: ${issue.labels.join(', ')}

---

${issue.body}
`.trim();
}
