import type { RunReport, GitHubIssue, GitHubIssueCreationResult, Suggestion } from './types';

// ============================================================================
// GitHub Issue Generation from Run Results
// ============================================================================

/**
 * Generate a GitHub issue body from an LLM suggestion
 */
export function generateIssueFromSuggestion(
  suggestion: Suggestion,
  runReport: RunReport
): GitHubIssue {
  const severityEmoji = {
    low: '🟡',
    medium: '🟠',
    high: '🔴',
    critical: '🚨',
  };

  const body = `## ${severityEmoji[suggestion.severity]} ${suggestion.title}

### Description
${suggestion.description}

### Context
- **Scenario**: ${runReport.scenarioName} (\`${runReport.scenarioId}\`)
- **Run ID**: \`${runReport.id}\`
- **Run Date**: ${runReport.startTime}
- **Status**: ${runReport.status}
- **Duration**: ${runReport.duration ? `${(runReport.duration / 1000).toFixed(2)}s` : 'N/A'}

### Environment
- **VS Code Target**: ${runReport.environment.vscodeTarget}
- **VS Code Version**: ${runReport.environment.vscodeVersion}
- **Platform**: ${runReport.environment.platform}
- **Copilot Channel**: ${runReport.environment.copilotChannel}

### Steps Summary
${runReport.steps.map(s => `- ${s.status === 'passed' ? '✅' : s.status === 'failed' ? '❌' : '⏭️'} Step \`${s.stepId}\`: ${s.status}${s.error ? ` - ${s.error}` : ''}`).join('\n')}

### Suggested Labels
${suggestion.labels.map(l => `\`${l}\``).join(', ')}

---
*Generated by VS Code Scenario Runner*
`;

  return {
    title: `[${suggestion.severity.toUpperCase()}] ${suggestion.title}`,
    body,
    labels: suggestion.labels,
  };
}

/**
 * Generate a GitHub issue from a scenario failure
 */
export function generateIssueFromFailure(runReport: RunReport): GitHubIssue {
  const failedSteps = runReport.steps.filter(s => s.status === 'failed');
  const failedAssertions = runReport.assertions.filter(a => !a.passed);

  const body = `## 🔴 Scenario Failed: ${runReport.scenarioName}

### Summary
The scenario \`${runReport.scenarioId}\` failed during automated testing.

### Run Details
- **Run ID**: \`${runReport.id}\`
- **Status**: \`${runReport.status}\`
- **Start Time**: ${runReport.startTime}
- **End Time**: ${runReport.endTime || 'N/A'}
- **Duration**: ${runReport.duration ? `${(runReport.duration / 1000).toFixed(2)}s` : 'N/A'}

### Environment
| Setting | Value |
|---------|-------|
| VS Code Target | ${runReport.environment.vscodeTarget} |
| VS Code Version | ${runReport.environment.vscodeVersion} |
| Platform | ${runReport.environment.platform} |
| Copilot Channel | ${runReport.environment.copilotChannel} |

### Failed Steps
${failedSteps.length > 0 ? failedSteps.map(s => `
#### Step: \`${s.stepId}\`
- **Duration**: ${s.duration ? `${s.duration}ms` : 'N/A'}
- **Error**: ${s.error || 'No error message'}
`).join('\n') : 'No failed steps'}

### Failed Assertions
${failedAssertions.length > 0 ? failedAssertions.map(a => `
#### Assertion: \`${a.assertionId}\`
- **Expected**: \`${JSON.stringify(a.expected)}\`
- **Actual**: \`${JSON.stringify(a.actual)}\`
- **Error**: ${a.error || 'No error message'}
`).join('\n') : 'No failed assertions'}

### Error
${runReport.error || 'No top-level error'}

### Artifacts
${runReport.artifacts.screenshots.length > 0 ? `- Screenshots: ${runReport.artifacts.screenshots.length} captured` : '- No screenshots'}
${runReport.artifacts.video ? '- Video recording available' : '- No video'}
${runReport.artifacts.logs ? '- Logs available' : '- No logs'}

---
*Generated by VS Code Scenario Runner*
`;

  const labels = ['bug', 'scenario-failure', `priority-${runReport.llmEvaluation?.suggestions?.[0]?.severity || 'medium'}`];

  return {
    title: `[FAILURE] ${runReport.scenarioName} - ${failedSteps[0]?.stepId || 'Unknown step'}`,
    body,
    labels,
  };
}

/**
 * Format issue preview for CLI display
 */
export function formatIssuePreview(issue: GitHubIssue): string {
  return `
╭─────────────────────────────────────────────────────────────────────────────╮
│ GITHUB ISSUE PREVIEW                                                        │
├─────────────────────────────────────────────────────────────────────────────┤
│ Title: ${issue.title.substring(0, 65).padEnd(65)} │
├─────────────────────────────────────────────────────────────────────────────┤
│ Labels: ${issue.labels.join(', ').substring(0, 64).padEnd(64)} │
├─────────────────────────────────────────────────────────────────────────────┤
│ Body Preview:                                                               │
│ ${issue.body.split('\n').slice(0, 5).map(l => l.substring(0, 73).padEnd(73)).join(' │\n│ ')} │
╰─────────────────────────────────────────────────────────────────────────────╯
`;
}

/**
 * Create a GitHub issue via the API
 * Requires GITHUB_TOKEN environment variable
 */
export async function createGitHubIssue(
  issue: GitHubIssue,
  repo: string
): Promise<GitHubIssueCreationResult> {
  const token = process.env.GITHUB_TOKEN;
  
  if (!token) {
    return {
      success: false,
      error: 'GITHUB_TOKEN environment variable not set',
    };
  }

  try {
    const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        title: issue.title,
        body: issue.body,
        labels: issue.labels,
        assignees: issue.assignees,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      return {
        success: false,
        error: `GitHub API error (${response.status}): ${errorBody}`,
      };
    }

    const data = await response.json();
    
    return {
      success: true,
      issueNumber: data.number,
      issueUrl: data.html_url,
    };
  } catch (error) {
    return {
      success: false,
      error: `Network error: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}
